// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RomainJ.MinieBicks.Data;

namespace RomainJ.MinieBicks.Data.Migrations
{
    [DbContext(typeof(MineBricksContext))]
    [Migration("20191119103815_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079");

            modelBuilder.Entity("RomainJ.MinieBicks.Data.Personne", b =>
                {
                    b.Property<Guid>("IdPersonne")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Nom");

                    b.Property<string>("Prenom");

                    b.Property<Guid?>("SuperieurIdPersonne");

                    b.HasKey("IdPersonne");

                    b.HasIndex("SuperieurIdPersonne");

                    b.ToTable("Personne");
                });

            modelBuilder.Entity("RomainJ.MinieBicks.Data.Role", b =>
                {
                    b.Property<Guid>("IdRole")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Nom");

                    b.HasKey("IdRole");

                    b.ToTable("Role");
                });

            modelBuilder.Entity("RomainJ.MinieBicks.Data.Personne", b =>
                {
                    b.HasOne("RomainJ.MinieBicks.Data.Personne", "Superieur")
                        .WithMany()
                        .HasForeignKey("SuperieurIdPersonne");
                });
#pragma warning restore 612, 618
        }
    }
}
